### ISSUE TITLE
Use Node Package Manager (NPM)

### ISSUE THREAD

**Issue by marcioviegas** [virgs/medium-next-gen-stats#1]
https://nodejs.org/en/knowledge/getting-started/npm/what-is-npm/

**Comment by virgs** [comment]
I don't get what you meant.
It is a google chrome extension, not a node project.

**Comment by marcioviegas** [comment]
NPM it is not just for a node project. It is to manage Javascript project dependencies. Don't close my Issues 👎

**Comment by virgs** [comment]
My bad. Due to the absence of replies, I thought I got you answered.

I see your point, but, given the nature of the project, I think adding NPM here is not required at all and I can't see how NPM would help here.
The browser itself, instructed by [the manifest](https://github.com/virgs/medium-next-gen-stats/blob/master/manifest.json), manages the project dependencies.

**Comment by marcioviegas** [comment]
Gotcha! Now we can close! Thanks!
