### ISSUE TITLE
Feature Requests + Earnings Bug

### ISSUE THREAD

**Issue by elibroftw** [virgs/medium-next-gen-stats#4]
First off, great extension, improves the statistics page.
- Add option for all time
- Add date to the label for each article beside the estimated read time
- The bug shown below for earnings pie chart.
![image](https://user-images.githubusercontent.com/21298211/120704978-3c855e80-c485-11eb-93cc-ce9b4a0964fc.png)

**Comment by virgs** [comment]
Great.

Just uploaded the .22 version (it usually takes some hours to be available) which includes:
- publication date of each article
- 1800 days range. Due to performance reasons, I don't think it'd be reasonable to enable all time option. Remember there are users with hundreds of articles with thousands of views each. It's a risk already to enable 1800 days, I'm sure some users will complain.

Given that I'm not an "earner" user, it's pretty much impossible for me to fix the earning pie chart bug. Sorry about that.
By the time I developed this feature, some users helped me sending their earnings data so I could work with. them

**Comment by elibroftw** [comment]
The earnings is just a rounding issue plus a formatting issue. Number are formatted like 2.,13 instead of 2.13 and sometimes they go on past two decimal places.

**Comment by virgs** [comment]
I see. I'm sure this is an easy thing to fix. But it becomes a really hard thing to do without the data.
Without the data, for instance, I can't know where the error happens, if it's in the data fetch, or in chart generation. :/

It would help a lot If you download your earnings data and send it to me (clicking the download button). You can change the values, if you want to, as long as you keep the consistency.
Another way to fix it is to fork the project and trying fixing it yourself. I even encourage you to do that. LOL

**Comment by elibroftw** [comment]
This is the json export. I renamed it to .txt so that I could upload it.
[medium-next-generation-stats.txt](https://github.com/virgs/medium-next-gen-stats/files/6598996/medium-next-generation-stats.txt)

**Comment by virgs** [comment]
Great. I'll work on this. I'll let you know as soon as I have it finished.
